### ISSUE TITLE
feat: short-form config

### ISSUE THREAD

**Issue by gildesmarais** [html2rss/html2rss#11]
the amount of typing to create a feed is too high.

instead of

```yaml
hotthai:
    channel:
      title: 'hotthai'
      url: https://hot-thai-kitchen.com/hot-thai-kitchen-newsletter/
      ttl: 720
    selectors:
      items:
        selector: '.mailpoet_archive li'
      title:
        selector: '.mailpoet_archive_subject > a'
      link:
        selector: '.mailpoet_archive_subject > a'
        extractor: 'href'
        post_process:
          name: 'parse_uri'
      updated:
        selector: '.mailpoet_archive_date'
        post_process:
          name: parse_time
```

it could become something shorter.

```yaml
hotthai:
  url: https://hot-thai-kitchen.com/hot-thai-kitchen-newsletter/
  ttl: 720
  items: '.mailpoet_archive li'
  title: '.mailpoet_archive_subject > a'
  link: '.mailpoet_archive_subject > a@href|parse_uri'
  updated: '.mailpoet_archive_date|parse_time'
```
