### ISSUE TITLE
Allow `selectors` articles to be enriched with auto_source's Scraper findings

### ISSUE THREAD

**Issue by gildesmarais** [html2rss/html2rss#206]
When using the 'traditional feed config' generation approach, it can be cumbersome to extract all the details for an article.

- [x] I'd love to see such config just to work:
	```yml
	channel:
	  url: http://example.com
	selectors:
	  items:
	    selector: 'div.card > div`
	    enhance: true
	  #…
    ```
- [x] and having `title` and `description` and `image` (and what else) automatically extracted using auto_source's Scrapers.
- [x] The automatically extracted information should never override attributes which the feed config explicitly specified.
- [x] allow cli usage: ie `html2rss auto --items-selector='.archive__item' URL`
- [x] Should this be enabled by default for a good UX?
