### ISSUE TITLE
feat(auto_source): make configurable via `config`

### ISSUE THREAD

**Issue by gildesmarais** [html2rss/html2rss#243]
Roughly like so:

```yml
channel:
  # …
auto_source:
  min_frequency: 3
  keep_different_domain: false
  disable_scrapers:
     - Html
```

- [x] Find compromise in verbosity and usablity (i.e. this would be explicity and clear `auto_source.clean_up.keep_different_domain = false`).
- [x] allow AutoSource::Scrapers to be configured individually
- [x] provide sensible defaults
