### ISSUE TITLE
published_at selector isn't grabbing time elements

### ISSUE THREAD

**Issue by riflesniper** [html2rss/html2rss#254]
hello, i've been toying around with this for the last little while, and while i've been able to get a nice feed out of it, the fact that it won't grab the dates i've put in the html is irritating me. 

as an example, here is the base html:

```
            <article class="artcard"><a href="img/2025/05-dp53.webp" target="long ass list of responsive images" loading="lazy"></a>
                <div class="description">
                    <h1>patron reward</h1>
                    <p>reward for aesonyx</p>
                </div>
            <time>2025-02-01 18:18</time>
            </article>
```

along with the config elements:

```
selectors:
  items:
    selector: ".artcard"
  title:
    selector: "h1"
  description:
    selector: "p"
  published_at:
    selector: "time"
    post_process:
      - name: parse_time
  enclosure:
    selector: "img"
    extractor: "attribute"
    attribute: "src"
    content_type: "image/webp"
  guid:
    - enclosure
```

and yet, when i run it through the terminal, it spits this out:

```
    <item>
      <title>patron reward</title>
      <description>reward for aesonyx</description>
      <enclosure url="https://riflesniper.art/portfolio/img/2025/05-dp53.webp"
        length="0"
        type="image/webp"/>
      <guid isPermaLink="false">146f7408e54686a353366d548739c293dd861d2b</guid>
    </item>
```

everything's fine except for a missing pubdate element. i've tried looking through the other config files to find examples of how to do it, but i could find none. is this a bug, or am i doing something wrong?
